[package]
name = "heibackend"
version = "0.1.0"
authors = ["shomasd <shomasd@ueda.info.waseda.ac.jp>"]

[dependencies]
ncurses = "5.99.0"
lazy_static = "1.4.0"

[lib]
name = "heilib"
crate-type = ["staticlib"]
file = "src/lib.rs"

